import Head from 'next/head';

// components
import Header from '../components/header';
import Results from '../components/results';

// utili
import requests from '../utilities/request';

export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu byvrd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico.png" />
      </Head>

      <Header />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
